/**
 * @packageDocumentation
 * @module api.functional.api.v1.user.2
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher, Primitive } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";

/**
 * 제목
 * 내용
 * 
 * @returns 리턴이 작성된 경우
 * 
 * @controller UsersController.getHello2()
 * @path GET /api/v1/user/2
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function getHello2
    (
        connection: IConnection
    ): Promise<getHello2.Output>
{
    return Fetcher.fetch
    (
        connection,
        getHello2.ENCRYPTED,
        getHello2.METHOD,
        getHello2.path()
    );
}
export namespace getHello2
{
    export type Output = Primitive<"hello2">;

    export const METHOD = "GET" as const;
    export const PATH: string = "/api/v1/user/2";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(): string
    {
        return `/api/v1/user/2`;
    }
}