/**
 * @packageDocumentation
 * @module api.functional.api.v1.user.5
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher, Primitive } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";

/**
 * 제목
 * 
 * @controller UsersController.getHello5()
 * @path GET /api/v1/user/5
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function getHello5
    (
        connection: IConnection
    ): Promise<getHello5.Output>
{
    return Fetcher.fetch
    (
        connection,
        getHello5.ENCRYPTED,
        getHello5.METHOD,
        getHello5.path()
    );
}
export namespace getHello5
{
    export type Output = Primitive<string>;

    export const METHOD = "GET" as const;
    export const PATH: string = "/api/v1/user/5";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(): string
    {
        return `/api/v1/user/5`;
    }
}