/**
 * @packageDocumentation
 * @module api.functional.api.v1.user.c
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher, Primitive } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";

/**
 * 제목
 * 
 * @tag tag_test
 * 
 * @controller UsersController.getHello8()
 * @path GET /api/v1/user/c
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function getHello8
    (
        connection: IConnection
    ): Promise<getHello8.Output>
{
    return Fetcher.fetch
    (
        connection,
        getHello8.ENCRYPTED,
        getHello8.METHOD,
        getHello8.path()
    );
}
export namespace getHello8
{
    export type Output = Primitive<"hello8">;

    export const METHOD = "GET" as const;
    export const PATH: string = "/api/v1/user/c";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(): string
    {
        return `/api/v1/user/c`;
    }
}