/**
 * @packageDocumentation
 * @module api.functional.api.v1.user.1
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher, Primitive } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";

/**
 * 제목
 * 내용
 * 
 * @controller UsersController.getHello()
 * @path GET /api/v1/user/1
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function getHello
    (
        connection: IConnection
    ): Promise<getHello.Output>
{
    return Fetcher.fetch
    (
        connection,
        getHello.ENCRYPTED,
        getHello.METHOD,
        getHello.path()
    );
}
export namespace getHello
{
    export type Output = Primitive<"hello">;

    export const METHOD = "GET" as const;
    export const PATH: string = "/api/v1/user/1";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(): string
    {
        return `/api/v1/user/1`;
    }
}