/**
 * @packageDocumentation
 * @module api.functional.api.v1.user.a
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher, Primitive } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";

/**
 * 제목
 * 
 * @controller UsersController.getHello6()
 * @path GET /api/v1/user/a
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function getHello6
    (
        connection: IConnection
    ): Promise<getHello6.Output>
{
    return Fetcher.fetch
    (
        connection,
        getHello6.ENCRYPTED,
        getHello6.METHOD,
        getHello6.path()
    );
}
export namespace getHello6
{
    export type Output = Primitive<"hello6">;

    export const METHOD = "GET" as const;
    export const PATH: string = "/api/v1/user/a";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(): string
    {
        return `/api/v1/user/a`;
    }
}