/**
 * @packageDocumentation
 * @module api.functional.api.v1.user.b
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher, Primitive } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";

/**
 * 제목이 길어야 나오는 것인지 테스트
 * 
 * @controller UsersController.getHello7()
 * @path GET /api/v1/user/b
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function getHello7
    (
        connection: IConnection
    ): Promise<getHello7.Output>
{
    return Fetcher.fetch
    (
        connection,
        getHello7.ENCRYPTED,
        getHello7.METHOD,
        getHello7.path()
    );
}
export namespace getHello7
{
    export type Output = Primitive<"hello7">;

    export const METHOD = "GET" as const;
    export const PATH: string = "/api/v1/user/b";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(): string
    {
        return `/api/v1/user/b`;
    }
}