/**
 * @packageDocumentation
 * @module api.functional.api.v1.user.3
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import { Fetcher, Primitive } from "@nestia/fetcher";
import type { IConnection } from "@nestia/fetcher";

/**
 * 제목
 * 
 * @controller UsersController.getHello3()
 * @path GET /api/v1/user/3
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export function getHello3
    (
        connection: IConnection
    ): Promise<getHello3.Output>
{
    return Fetcher.fetch
    (
        connection,
        getHello3.ENCRYPTED,
        getHello3.METHOD,
        getHello3.path()
    );
}
export namespace getHello3
{
    export type Output = Primitive<"hello3">;

    export const METHOD = "GET" as const;
    export const PATH: string = "/api/v1/user/3";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(): string
    {
        return `/api/v1/user/3`;
    }
}